name: native_ads
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # state management
  provider: ^6.0.5

  # responsive design
  flutter_screenutil: ^5.9.1
  auto_size_text: ^3.0.0

  # firebase
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.4
  firebase_storage: ^11.7.6
  
  # language support
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  hive_flutter: ^1.1.0
  easy_localization: ^3.0.7

  ## api & network
  dio: ^5.7.0
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  flutter_lints: ^2.0.1
  json_serializable: ^6.7.0
  flutter_gen: ^5.0.2
  flutter_gen_runner: ^5.5.0+1
  easy_localization_generator: ^0.3.2


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/translations/

flutter_gen:
  output: lib/src/core/generated/assets

  integrations:
    flutter_svg: true
    lottie: true
